version: "3.3"
services:
  node:
    # build: ..
    image: iczc/billboard:1.0.0
    container_name: billboardd
    ports:
      - "26657:26657"
    volumes:
      - ./genesis:/root/.billboardd
    command: billboardd start

  lcd:
    # build: ..
    image: iczc/billboard:1.0.0
    container_name: light-client-daemon
    expose:
      - "1317"
    links:
      - node
    command: billboardcli rest-server --laddr tcp://0.0.0.0:1317 --node tcp://node:26657 --trust-node=true
    depends_on:
      - node

  api:
    # build: playground
    image: iczc/billboard-playground-api:latest
    container_name: playground-api
    expose:
      - "5000"
    links:
      - lcd
    depends_on:
      - lcd

  web:
    # build: playground/web
    image: iczc/billboard-playground-web:latest
    container_name: playground-web
    ports:
      - "80:80"
    links:
      - api
    env_file:
      - ./playground/.env
    volumes:
      - ./playground/nginx:/etc/nginx/templates
    depends_on:
      - api
